/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class ArticulataTest {
    @Test
    public void testAppHasAGreeting() {
        Articulata classUnderTest = new Articulata();
    }
}
