/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.articulatagame.Articulata;
import org.junit.Test;

public class ArticulataTest {
    @Test
    public void testAppHasAGreeting() {
        Articulata classUnderTest = new Articulata();
    }
}
